import type { FormEvent } from 'react'
import { useState, useEffect } from 'react'
import { Calculator, Plus, ArrowUpCircle, ArrowDownCircle, TrendingUp, Wallet, Filter, Search, Trash2, Edit3, FileText } from 'lucide-react'
import { apiClient } from '../api/client'

interface Transaction { id: number; type: 'income' | 'expense'; amount: number; description: string; category: string; date: string; status?: string }
interface Summary { income: number; expenses: number; balance: number; }

export default function Accounting() {
 const [transactions,setTransactions]=useState<Transaction[]>([]); const [summary,setSummary]=useState<Summary>({income:0,expenses:0,balance:0}); const [loading,setLoading]=useState(true); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Transaction|null>(null); const [filter,setFilter]=useState<'all'|'income'|'expense'>('all'); const [search,setSearch]=useState(''); const [form,setForm]=useState({type:'income' as 'income'|'expense',amount:'',description:'',category:'Другое',date:new Date().toISOString().slice(0,10)}); const [error,setError]=useState('')
 const load=async()=>{setLoading(true);try{const [t,s]=await Promise.all([apiClient.get('/api/accounting/transactions'),apiClient.get('/api/accounting/summary')]);setTransactions(Array.isArray(t.data)?t.data:t.data?.items??[]);setSummary(s.data)}catch(e:any){setError(e?.response?.data?.detail||'Не удалось загрузить бухгалтерию')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const submit=async(e:FormEvent)=>{e.preventDefault();try{const payload={...form,amount:Number(form.amount)};if(editing) await apiClient.put(`/api/accounting/transactions/${editing.id}`,payload);else await apiClient.post('/api/accounting/transactions',payload);setShowForm(false);setEditing(null);setForm({type:'income',amount:'',description:'',category:'Другое',date:new Date().toISOString().slice(0,10)});load()}catch(err:any){setError(err?.response?.data?.detail||'Не удалось сохранить операцию')}}
 const remove=async(id:number)=>{if(!confirm('Удалить операцию?'))return;try{await apiClient.delete(`/api/accounting/transactions/${id}`);load()}catch(err:any){setError(err?.response?.data?.detail||'Не удалось удалить операцию')}}
 const startEdit=(t:Transaction)=>{setEditing(t);setForm({type:t.type,amount:String(t.amount),description:t.description,category:t.category,date:t.date.slice(0,10)});setShowForm(true)}
 const filtered=transactions.filter(t=>(filter==='all'||t.type===filter)&&(!search||`${t.description} ${t.category}`.toLowerCase().includes(search.toLowerCase())))
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-orange-50 p-3 text-orange-600"><Calculator className="h-6 w-6"/></div><div><h1 className="text-3xl font-black text-slate-950">Бухгалтерия</h1><p className="text-sm text-slate-500">Доходы, расходы и финансовый контроль</p></div></div></div><button onClick={()=>{setEditing(null);setShowForm(true)}} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-orange-500 px-5 py-3 font-bold text-white shadow-lg shadow-orange-500/20 hover:bg-orange-600"><Plus className="h-5 w-5"/>Добавить операцию</button></header>
 {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <div className="grid gap-4 md:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Доходы</span><ArrowUpCircle className="h-5 w-5 text-emerald-500"/></div><div className="mt-3 text-2xl font-black text-slate-950">{summary.income.toLocaleString('ru-RU')} ₽</div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Расходы</span><ArrowDownCircle className="h-5 w-5 text-rose-500"/></div><div className="mt-3 text-2xl font-black text-slate-950">{summary.expenses.toLocaleString('ru-RU')} ₽</div></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Баланс</span><Wallet className="h-5 w-5 text-orange-500"/></div><div className="mt-3 text-2xl font-black text-slate-950">{summary.balance.toLocaleString('ru-RU')} ₽</div></div></div>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск операций…" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-orange-400"/></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-slate-400"/>{(['all','income','expense'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} className={`rounded-xl px-3 py-2 text-xs font-bold ${filter===v?'bg-slate-950 text-white':'bg-slate-100 text-slate-600'}`}>{v==='all'?'Все':v==='income'?'Доходы':'Расходы'}</button>)}</div></div>{loading?<div className="p-8 text-center text-slate-400">Загрузка…</div>:filtered.length===0?<div className="p-12 text-center"><FileText className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 font-semibold text-slate-600">Операций пока нет</p></div>:<div className="overflow-auto"><table className="min-w-full"><thead><tr className="border-b bg-slate-50 text-xs uppercase text-slate-400"><th className="px-5 py-3 text-left">Дата</th><th className="px-5 py-3 text-left">Описание</th><th className="px-5 py-3 text-left">Категория</th><th className="px-5 py-3 text-right">Сумма</th><th className="px-5 py-3 text-right">Действия</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-b last:border-0"><td className="px-5 py-4 text-sm text-slate-500">{new Date(t.date).toLocaleDateString('ru-RU')}</td><td className="px-5 py-4 font-semibold text-slate-800">{t.description}</td><td className="px-5 py-4 text-sm text-slate-500">{t.category}</td><td className={`px-5 py-4 text-right font-bold ${t.type==='income'?'text-emerald-600':'text-rose-600'}`}>{t.type==='income'?'+':'−'}{t.amount.toLocaleString('ru-RU')} ₽</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button onClick={()=>startEdit(t)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><Edit3 className="h-4 w-4"/></button><button onClick={()=>remove(t.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>}</section>
 {showForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">{editing?'Изменить операцию':'Новая операция'}</h2><div className="mt-5 grid gap-4"><div className="grid grid-cols-2 gap-2">{(['income','expense'] as const).map(v=><button type="button" key={v} onClick={()=>setForm({...form,type:v})} className={`rounded-xl p-3 text-sm font-bold ${form.type===v?'bg-slate-950 text-white':'bg-slate-100 text-slate-600'}`}>{v==='income'?'Доход':'Расход'}</button>)}</div><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Сумма" className="rounded-xl border border-slate-200 p-3"/><input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Описание" className="rounded-xl border border-slate-200 p-3"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Категория" className="rounded-xl border border-slate-200 p-3"/><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="rounded-xl border border-slate-200 p-3"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl px-4 py-3 font-bold text-slate-600">Отмена</button><button className="rounded-xl bg-orange-500 px-5 py-3 font-bold text-white">Сохранить</button></div></div></form></div>}
 </div>
}
