import { Link } from 'react-router-dom'
import { ArrowRight, ShieldCheck, Smartphone, Apple, Download as DownloadIcon, Sparkles } from 'lucide-react'
import apiClient from '../api/client'
import { useEffect, useState } from 'react'

export default function Downloads(){
 const [apkAvailable,setApkAvailable]=useState(false); const [iosUrl,setIosUrl]=useState('')
 useEffect(()=>{apiClient.get('/api/downloads/status').then(r=>{setApkAvailable(!!r.data?.android_available);setIosUrl(r.data?.ios_url||'')}).catch(()=>{})},[])
 return <div className="mx-auto max-w-6xl space-y-6">
  <section className="relative overflow-hidden rounded-[30px] border border-orange-100 bg-gradient-to-br from-orange-50 via-white to-amber-50 px-6 py-10 sm:px-10"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full bg-orange-200/40 blur-3xl"/><div className="relative grid items-center gap-8 lg:grid-cols-[1fr_320px]"><div><div className="eyebrow">Мобильное приложение</div><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-5xl">Ваш кабинет всегда с вами.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-500 sm:text-base">Один аккаунт, те же клиенты, документы, финансы и <b className="text-slate-800">Светлана</b> — теперь в мобильном формате.</p></div><div className="rounded-[24px] border border-white/80 bg-white/80 p-5 shadow-sm"><div className="flex items-center gap-3"><img src="/static/logo-mir-samozanyatykh.png" alt="Мир Самозанятых" className="h-12 w-12 object-contain"/><div><div className="font-black text-slate-950">Мир Самозанятых</div><div className="text-xs text-slate-500">Android · iOS</div></div></div><div className="mt-4 flex items-center gap-3"><div className="h-12 w-12 overflow-hidden rounded-2xl bg-[#171a22]"><img src="/static/svetlana/face.png" alt="Светлана" className="h-full w-full object-cover object-top"/></div><div className="text-xs text-slate-600">Светлана тоже<br/>в приложении</div></div></div></div></section>
  <div className="grid gap-5 md:grid-cols-2"><DownloadCard icon={Smartphone} title="Android" text={apkAvailable?'Установочный APK готов к загрузке.':'APK пока не опубликован на сервере.'} action={apkAvailable?'/downloads/android':undefined} label="Скачать APK" available={apkAvailable}/><DownloadCard icon={Apple} title="iPhone и iPad" text={iosUrl?'Официальная ссылка на App Store подключена.':'Ссылка на iOS-сборку ещё не подключена.'} action={iosUrl||undefined} label="Открыть App Store" available={!!iosUrl}/></div>
  <div className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-start gap-4"><div className="rounded-2xl bg-orange-50 p-3 text-orange-600"><ShieldCheck className="h-5 w-5"/></div><div><h2 className="font-black text-slate-950">Безопасная загрузка</h2><p className="mt-1 text-sm leading-6 text-slate-500">Сайт показывает кнопку только тогда, когда настоящий бинарный файл или ссылка действительно опубликованы.</p></div></div></div>
  <div className="flex justify-center"><Link to="/svetlana" className="inline-flex items-center gap-2 text-sm font-bold text-orange-600">Спросить Светлану о приложении <Sparkles className="h-4 w-4"/><ArrowRight className="h-4 w-4"/></Link></div>
 </div>
}
function DownloadCard({icon:Icon,title,text,action,label,available}:{icon:any,title:string,text:string,action?:string,label:string,available:boolean}){return <div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-2xl bg-orange-50 p-3 text-orange-600"><Icon className="h-6 w-6"/></div><div className="min-w-0 flex-1"><h2 className="font-black text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div><div className="mt-6">{available&&action?<a href={action} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-sm font-bold text-white hover:bg-orange-600"><DownloadIcon className="h-4 w-4"/>{label}</a>:<div className="rounded-xl bg-slate-50 px-4 py-3 text-xs font-semibold text-slate-400">Публикация ещё не подключена</div>}</div></div>}
